language: python
python:
  - "2.7"

before_install:
  - pip install codecov

install:
  - pip install -e git+https://github.com/tonioo/modoboa.git#egg=modoboa
  - pip install -q factory-boy testfixtures
  - python setup.py -q develop
  - pip install -q psycopg2

before_script:
  - psql -c 'create database modoboa_test;' -U postgres

script:
  - cd test_project
  - PYTHONPATH=".." DJANGO_SETTINGS_MODULE="test_project.settings" python -c "import modoboa_postfix_autoreply.tests"
  - coverage run --source ../modoboa_postfix_autoreply manage.py test modoboa_postfix_autoreply.tests

after_success:
  - codecov

